jenkins:
    systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
    remotingSecurity:
        enabled: true
    securityRealm:
        local:
            allowsSignup: false
            users:
                - id: "chocolateen"
                  name: "Hugo"
                  password: ${USER_CHOCOLATEEN_PASSWORD}
                - id: "vaugie_g"
                  name: "Garance"
                  password: ${USER_VAUGIE_G_PASSWORD}
                - id: "i_dont_know"
                  name: "Jeremy"
                  password: ${USER_I_DONT_KNOW_PASSWORD}
                - id: "nasso"
                  name: "Nassim"
                  password: ${USER_NASSO_PASSWORD}
    authorizationStrategy:
        roleBased:
            roles:
                global:
                    - name: "admin"
                      description: "Marvin master"
                      permissions:
                        - "Overall/Administer"
                      assignments:
                        - "chocolateen"
                        - "admin"
                    - name: "ape"
                      description: "Pedagogical team member"
                      permissions:
                        - "Job/Build"
                        - "Job/Workspace"
                      assignments:
                        - "i_dont_know"
                    - name: "gorilla"
                      description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
                      permissions:
                        - "Job/Build"
                        - "Job/Workspace"
                        - "Job/Create"
                        - "Job/Configure"
                        - "Job/Delete"
                        - "Job/Move"
                        - "Job/Cancel"
                      assignments:
                        - "vaugie_g"
                    - name: "assist"
                      description: "Assistant"
                      permissions:
                        - "Job/Read"
                        - "Job/Workspace"
                      assignments:
                        - "nasso"
security:
    globalJobDslSecurityConfiguration:
      useScriptSecurity: false
jobs:
    - script: >
        folder('Tools') {
            description('Folder for miscellaneous tools.')
        }

        job('Tools/clone-repository') {
            parameters {
                stringParam('GIT_REPOSITORY_URL', '', 'Git URL of the repository to clone')
            }
            steps {
                shell('git clone $GIT_REPOSITORY_URL')
            }
            wrappers {
                preBuildCleanup()
            }
        }

        job('Tools/SEED') {
            parameters {
                stringParam('GITHUB_NAME', '', 'GitHub repository owner/repo_name (e.g.: "EpitechIT31000/chocolatine")')
                stringParam('DISPLAY_NAME', '', 'Display name for the job')
            }
            steps {
                dsl {
                    text('''
                        job("$DISPLAY_NAME") {
                            wrappers {
                                preBuildCleanup()
                            }
                            scm {
                                github("$GITHUB_NAME")
                            }
                            triggers {
                                scm('* * * * *')
                            }
                            steps {
                                shell('make fclean')
                                shell('make')
                                shell('make test')
                                shell('make clean')
                            }
                        }
                    ''')
                }
            }
        }
